name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-tests-and-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install dev dependencies
        run: |
          pip install .[dev]

      - name: Run style check
        run: make style

      - name: Run tests
        run: make test
